version: '3'

services:                        
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage_joomla_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: Akarsh
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydbjoomla

  joom:
    image: joomla:3.9-php7.2-apache
    restart: always
    depends_on:
      - dbos
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: dbos:3306
      JOOMLA_DB_USER: Akarsh
      JOOMLA_DB_PASSWORD: redhat
      JOOMLA_DB_NAME: mydbjoomla
    volumes:
      - joomla_storage_new:/var/www/html
volumes:
        mysql_storage_joomla_new:
        joomla_storage_new:
